export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const EMPLOYEE_NOT_FOUND = 'EMPLOYEE_NOT_FOUND';

export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';
export const SUBMIT_REGISTRATION_FORM_SUCCESS = 'SUBMIT_REGISTRATION_FORM_SUCCESS';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ERROR_STATUS = 'ERROR_STATUS';