export const SET_EMPLOYEE_DATA = 'SET_EMPLOYEE_DATA';
export const FETCH_EMPLOYEE_DATA = 'FETCH_EMPLOYEE_DATA';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const FETCH_SEARCHED_EMPLOYEE = 'FETCH_SEARCHED_EMPLOYEE';